# Generated by Django 6.0.7 on 2026-07-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
